name: Run pre-commits and tests

on:
  push:
     branches:
       main
  workflow_dispatch:

jobs:
  pre-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r frozen-requirements.txt
          pre-commit install
      - name: Run pre-commits
        run: |
          pre-commit run --all-files

  test:
    needs: pre-commits
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r frozen-requirements.txt
      - name: Test with pytest
        run: |
          pytest tests
